# Generated by Django 3.0.6 on 2020-08-15 10:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_manager_name': 'objectsNew', 'ordering': ('-publish',)},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objectsNew', django.db.models.manager.Manager()),
            ],
        ),
    ]
